

datalad_url: 'https://github.com/OpenNeuroDatasets/{dataset}.git'

datasets:
  ds002168:
    version: 1.1.0
    expand:
      file: 'sub-{subject}/anat/*'
      wildcards:
        subject: 
          - 1425
          - 1428
    modality: T2w


versions:
  v1.2.0: 
    container: /srv/containers/hippunfold_v1.2.0.sif
  v1.2.1: 
    container: /srv/containers/hippunfold_v1.2.1.sif
  v1.2.1-synthseg: 
    container: /srv/containers/hippunfold_v1.2.1_synthsegmodelonly.sif

